#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i 's|#error_page 404 /404.html;|error_page 404 /custom_404.html;|'
	/etc/nginx/sites-available/default
sudo sed -i 's|#location = /404.html {|loccation = /custom_404.html {|'
	/etc/nginx/sites-available/default
sudo sed -i 's|#    internal;|    internal;|'
       	/etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
