#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# custom HTTP header must be X-Served-By
# value of the custom HTTP header must be the hostname
# of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '11i\\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
echo 'Hello World!' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
